import React, { useState } from "react";

import { GlobalStyles } from "./GlobalStyles";
import { Button, Display, CalculatorWrapper } from "./components";

function App() {
  const [data, setData] = useState("0");
  const [dataArray, setArray] = useState([]);
  console.log(dataArray);

  return (
    <>
      <GlobalStyles />
      <CalculatorWrapper>
        <Display id="display" data={data} />
        <Button
          id="clear"
          input="clear"
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="seven"
          input="7"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="eight"
          input="8"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="nine"
          input="9"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="multiply"
          input="*"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="four"
          input="4"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="five"
          input="5"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="six"
          input="6"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="divide"
          input="/"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="one"
          input="1"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="two"
          input="2"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="three"
          input="3"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="add"
          input="+"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="decimal"
          input="."
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="zero"
          input="0"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="equals"
          input="="
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
        <Button
          id="subtract"
          input="-"
          data={data}
          setData={setData}
          dataArray={dataArray}
          setArray={setArray}
        />
      </CalculatorWrapper>
    </>
  );
}

export default App;
